//====================CART=====================
export const ADD_PLACE = 'ADD_PLACE';



export const CART_ITEM_LOADING = 'CART_ITEM_LOADING';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CART_ITEM_FAIL = 'CART_ITEM_FAIL';
export const CART_ITEM_RESET = 'CART_ITEM_RESET';
export const CART_ITEM_PAGE_CHANGE = 'CART_ITEM_PAGE_CHANGE';



export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CART_BUTTON_LABEL = 'CART_BUTTON_LABEL';

//====================Address=====================

export const ADDRESS_DETAIL = 'ADDRESS_DETAIL';
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const FETCH_PARTICULAR_ADDRESS = 'FETCH_PARTICULAR_ADDRESS';

//====================Wishlist=====================

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';

//====================Categories=====================

export const CATEGORY_LIST_LOADING = 'CATEGORY_LIST_LOADING';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';
export const CATEGORY_LIST_RESET = 'CATEGORY_LIST_RESET';
export const CATEGORY_PAGE_CHANGE = 'CATEGORY_PAGE_CHANGE';
export const SUB_CATEGORY_LIST = 'SUB_CATEGORY_LIST';

//====================Product List=====================
export const PRODUCT_LIST_LOADING = 'PRODUCT_LIST_LOADING';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
export const PRODUCT_LIST_RESET = 'PRODUCT_LIST_RESET';
export const PRODUCT_LIST_PAGE_CHANGE = 'PRODUCT_LIST_PAGE_CHANGE';



export const PRODUCT_DETAIL_DATA_LOADING = 'PRODUCT_DETAIL_DATA_LOADING';
export const PRODUCT_DETAIL_DATA_SUCCESS = 'PRODUCT_DETAIL_DATA_SUCCESS';
export const PRODUCT_DETAIL_DATA_RESET = 'PRODUCT_DETAIL_DATA_RESET';
export const PRODUCT_DETAIL_DATA_FAILED = 'PRODUCT_DETAIL_DATA_FAILED';


export const PRODUCT_DETAIL_INFO_STORE = 'PRODUCT_DETAIL_INFO_STORE';

export const PRODUCT_BUTTON_TAPPED = 'PRODUCT_BUTTON_TAPPED';


export const ORDER_LIST_LOADING = 'ORDER_LIST_LOADING';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';
export const ORDER_LIST_RESET = 'ORDER_LIST_RESET';
export const ORDER_LIST_PAGE_CHANGE = 'ORDER_LIST_PAGE_CHANGE';


export const ORDER_DETAIL_DATA_LOADING = 'ORDER_DETAIL_DATA_LOADING';
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS';
export const ORDER_DETAIL_FAIL = 'ORDER_DETAIL_FAIL';
export const ORDER_DETAIL_RESET = 'ORDER_DETAIL_RESET';


export const BUY_NOW_LIST_LOADING = 'BUY_NOW_LIST_LOADING';
export const BUY_NOW_LIST_SUCCESS = 'BUY_NOW_LIST_SUCCESS';
export const BUY_NOW_LIST_FAIL = 'BUY_NOW_LIST_FAIL';


export const HOME_DATA_LOADING = 'HOME_DATA_LOADING';
export const HOME_DATA_SUCCESS = 'HOME_DATA_SUCCESS';
export const HOME_DATA_FAIL = 'HOME_DATA_FAIL';

export const UPADTE_FEATURED_CART = 'UPADTE_FEATURED_CART';




export const PRODUCT_FILTER_BY_CATEGORY_SUCCESS = 'PRODUCT_FILTER_BY_CATEGORY_SUCCESS';





//====================USER REDUCER=====================
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const UPDATE_NAME_EMAIL = 'UPDATE_NAME_EMAIL';


