export default {
    home: require('../assets/images/home.png'),
    homeSelected: require('../assets/images/homeSelected.png'),
    categories: require('../assets/images/categories.png'),
    cart: require('../assets/images/cart.png'),
    cartSelected: require('../assets/images/cartSelected.png'),
    profile: require('../assets/images/profile.png'),
    backIcon: require(`../assets/images/backArrow.png`),
    searchIcon: require(`../assets/images/search_grey.png`),
    bannerImg: require(`../assets/images/banner.png`),
    mobile: require(`../assets/images/mobile.png`),
    mobile2: require(`../assets/images/mobile2.png`),
    mobile3: require(`../assets/images/mobile3.png`),
    mobile4: require(`../assets/images/mobile4.png`),
    mobile5: require(`../assets/images/mobile5.png`),
    mobile6: require(`../assets/images/mobile6.png`),
    like: require(`../assets/images/like.png`),
    star: require(`../assets/images/star.png`),
}